### PR TITLE
fix(CommonJS idiom) Fixes directory references in CommonJS idiom

### PR DESCRIPTION
**Pull request by kcjmowright**
- Added fix to handle directory references in imports (CommonJS idiom) by assuming the file should be directory + index.d.ts
- Added test.

Resolves Issue #38 @see https://github.com/TypeStrong/dts-bundle/issues/38

### CODE REVIEW

**Comment by thefabulousdev** [comment]
@Bartvds || @tolemac can someone take a look and hopefully approve this PR? Currently facing the issue this solves.

**Comment by tolemac** [comment]
I would like to have only changes related to the commit message in each commit.
I think you would have to make a separate PR for fix the format (white spaces, new lines, ...)

Could you leave only changes related to the PR title?

**Comment by kcjmowright** [comment]
I'm a bit busy at the moment.  I'll try to amend the commit in the next day or so.

**Comment by tolemac** [comment]
@kcjmowright Its good for now.
I'm going to merge it and publish npm package.
Thanks a lot.

**Pull request merged**
